# Generated by Django 4.2.6 on 2023-12-28 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('operation_code', models.CharField(max_length=20, null=True)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
                ('match_results', models.ManyToManyField(to='match.matchresult')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
