# Generated by Django 4.2.16 on 2024-12-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_remove_bet_match_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='operation_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
