# Generated by Django 4.2.16 on 2025-01-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_alter_bet_operation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='points',
        ),
    ]
