# Generated by Django 4.2.16 on 2025-02-17 00:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_matchresult_bet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0007_round_is_general_round'),
        ('bet', '0004_remove_bet_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bet',
            new_name='BetRound',
        ),
    ]
