# Generated by Django 4.2.16 on 2025-02-17 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0007_round_is_general_round'),
        ('bet', '0007_alter_betround_round_alter_betround_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetLeague',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('operation_code', models.CharField(blank=True, max_length=20, null=True)),
                ('winner', models.BooleanField(default=False)),
                ('is_last_visited_league', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='betround',
            name='bet_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_rounds', to='bet.betleague'),
        ),
    ]
