# Generated by Django 4.2.16 on 2025-02-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0008_betleague_betround_bet_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betround',
            name='user',
        ),
    ]
