# Generated by Django 4.2.16 on 2025-04-09 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_league_coins_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bet', '0009_remove_betround_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betleague',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_leagues', to='league.league'),
        ),
        migrations.AlterField(
            model_name='betleague',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_leagues', to=settings.AUTH_USER_MODEL),
        ),
    ]
