# Generated by Django 4.2.16 on 2025-04-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0010_alter_betleague_league_alter_betleague_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betleague',
            old_name='winner',
            new_name='winner_first',
        ),
        migrations.RenameField(
            model_name='betround',
            old_name='winner',
            new_name='winner_first',
        ),
        migrations.AddField(
            model_name='betleague',
            name='winner_second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betleague',
            name='winner_third',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betround',
            name='winner_second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betround',
            name='winner_third',
            field=models.BooleanField(default=False),
        ),
    ]
