# Generated by Django 4.2.16 on 2025-04-30 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0011_rename_winner_betleague_winner_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betround',
            name='bet_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_rounds', to='bet.betleague'),
        ),
    ]
