# Generated by Django 4.2.6 on 2024-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_appuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=models.ImageField(default='default-profile-image.png', upload_to='profile'),
        ),
    ]
