# Generated by Django 4.2.6 on 2024-01-02 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_appuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
