# Generated by Django 4.2.6 on 2024-04-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_appuser_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='birthdate',
        ),
    ]
