# Generated by Django 4.2.16 on 2025-04-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_remove_appuser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='coins',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
