# Generated by Django 4.2.16 on 2025-08-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_coingrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
