# Generated by Django 4.2.16 on 2025-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_appuser_instagram_username_appuser_twitter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='coins',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
