# Generated by Django 4.2.16 on 2025-09-23 07:29

from django.db import migrations


def get_referral_code_generator(apps, schema_editor):
    from apps.app_user.utils import generate_referral_code

    AppUser = apps.get_model('app_user', 'AppUser')
    for user in AppUser.objects.all():
        user.referral_code = generate_referral_code()
        user.save(update_fields=['referral_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_appuser_referral_code'),
    ]

    operations = [
        migrations.RunPython(
            get_referral_code_generator,
            reverse_code=migrations.RunPython.noop
        )
    ]
