# Generated by Django 4.2.16 on 2025-09-23 07:29

import apps.app_user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_appuser_generate_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='referral_code',
            field=models.CharField(blank=True, default=apps.app_user.utils.generate_referral_code, max_length=12, null=True, unique=True),
        ),
    ]
