# Generated by Django 4.2.16 on 2025-09-26 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_appuser_generate_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coingrant',
            name='reward_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ad reward'), (1, 'App review'), (2, 'Daily'), (3, 'Referral Signup'), (4, 'League winner'), (5, 'Referral Earned')]),
        ),
    ]
