# Generated by Django 5.2.9 on 2026-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0014_appuser_referred_by_alter_coingrant_reward_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='avatars/')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
