# Generated by Django 5.2.9 on 2026-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.IntegerField(choices=[(0, 'PUBLIC'), (1, 'PRIVATE')], default=0),
        ),
    ]
