# Generated by Django 4.2.16 on 2024-11-10 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_remove_bet_match_results'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bet.bet'),
        ),
    ]
