# Generated by Django 4.2.16 on 2025-01-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_matchresult_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Pending'), (2, 'Finalized'), (3, 'Cancelled')], default=0, verbose_name='State of the match'),
        ),
    ]
