# Generated by Django 4.2.16 on 2025-01-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_match_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
