# Generated by Django 4.2.16 on 2025-01-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_remove_bet_points'),
        ('match', '0004_matchresult_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_result', to='bet.bet'),
        ),
    ]
