# Generated by Django 4.2.16 on 2025-02-17 01:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0006_alter_betround_round_alter_betround_user'),
        ('match', '0005_alter_matchresult_bet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='bet',
            new_name='bet_round',
        ),
    ]
