# Generated by Django 4.2.16 on 2025-02-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0007_alter_betround_round_alter_betround_user'),
        ('match', '0006_remove_matchresult_bet_matchresult_bet_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='bet_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_results', to='bet.betround'),
        ),
    ]
