# Generated by Django 4.2.16 on 2025-03-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_alter_match_round_alter_match_team_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'verbose_name': 'Match Result', 'verbose_name_plural': 'Match results'},
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='goals_team_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='goals_team_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
