# Generated by Django 4.2.16 on 2025-05-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_alter_matchresult_bet_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='match.match'),
        ),
    ]
