# Generated by Django 4.2.16 on 2025-05-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_alter_matchresult_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Pending'), (2, 'Finalized'), (3, 'Cancelled'), (4, 'Postponed'), (5, 'Preplayed')], default=0, verbose_name='State of the match'),
        ),
    ]
