# Generated by Django 4.2.16 on 2025-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_alter_match_match_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='is_exact',
            field=models.BooleanField(default=False, verbose_name='Exact result'),
        ),
    ]
