# Generated by Django 5.2.9 on 2026-02-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_matchresult_is_exact'),
        ('payment', '0002_paidleagueconfig_start_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='paid_bet_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='payment.paidbetround'),
        ),
    ]
