# Generated by Django 5.2.9 on 2026-02-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0017_league_minimum_coins_first_prize_and_more'),
        ('match', '0014_matchresult_is_exact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidLeagueConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('is_paid_mode_enabled', models.BooleanField(default=False)),
                ('round_price_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('league_price_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_config', to='league.league')),
            ],
            options={
                'verbose_name': 'Paid League Config',
                'verbose_name_plural': 'Paid League Configs',
            },
        ),
        migrations.CreateModel(
            name='PaidPrizePool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('is_league_pool', models.BooleanField(default=False)),
                ('total_pool_ars', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distributed', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_prize_pools', to='league.league')),
                ('round', models.ForeignKey(blank=True, help_text='Null for league-level pool', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_prize_pools', to='league.round')),
            ],
            options={
                'verbose_name': 'Paid Prize Pool',
                'verbose_name_plural': 'Paid Prize Pools',
            },
        ),
        migrations.CreateModel(
            name='PaidWinner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('prize_amount_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Contacted'), (2, 'Paid')], default=0)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin about payout status', null=True)),
                ('prize_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='payment.paidprizepool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paid Winner',
                'verbose_name_plural': 'Paid Winners',
                'ordering': ['prize_pool', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('payment_type', models.CharField(choices=[('round', 'Round'), ('league', 'League')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=15)),
                ('mp_preference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='MercadoPago Preference ID')),
                ('mp_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='MercadoPago Payment ID')),
                ('gross_amount_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize_pool_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_reference', models.CharField(help_text='Unique reference for MercadoPago tracking', max_length=100, unique=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='league.league')),
                ('round', models.ForeignKey(blank=True, help_text='Null for full league payments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='league.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='PaidBetRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('winner_first', models.BooleanField(default=False)),
                ('winner_second', models.BooleanField(default=False)),
                ('winner_third', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_bet_rounds', to='league.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_bet_rounds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_bet_rounds', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Paid Bet Round',
                'verbose_name_plural': 'Paid Bet Rounds',
                'unique_together': {('user', 'round')},
            },
        ),
        migrations.CreateModel(
            name='PaidMatchResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('goals_team_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_team_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('is_exact', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_match_results', to='match.match')),
                ('paid_bet_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_match_results', to='payment.paidbetround')),
            ],
            options={
                'verbose_name': 'Paid Match Result',
                'verbose_name_plural': 'Paid Match Results',
                'unique_together': {('paid_bet_round', 'match')},
            },
        ),
    ]
