# Generated by Django 5.2.9 on 2026-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidleagueconfig',
            name='start_round_number',
            field=models.PositiveIntegerField(default=1, help_text='First round number where paid mode is available (e.g., 1, 3, 5)'),
        ),
    ]
