# Generated by Django 5.2.9 on 2026-02-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_league_minimum_coins_first_prize_and_more'),
        ('payment', '0002_paidleagueconfig_start_round_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidwinner',
            options={'verbose_name': 'Paid Winner', 'verbose_name_plural': 'Paid Winners'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterField(
            model_name='paidleagueconfig',
            name='start_round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paidprizepool',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_prize_pools', to='league.round'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='league.round'),
        ),
        migrations.DeleteModel(
            name='PaidMatchResult',
        ),
    ]
