# Generated by Django 5.2.9 on 2026-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paidwinner_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidprizepool',
            name='minimum_pool_ars',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=12),
        ),
    ]
