# Generated by Django 4.2.16 on 2025-02-28 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0009_league_logo_url_team_badge_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('token_id', models.CharField(max_length=150)),
                ('device_id', models.CharField(blank=True, max_length=150, null=True)),
                ('leagues', models.ManyToManyField(to='league.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
