# Generated by Django 4.2.16 on 2025-03-19 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_alter_fcmtoken_device_id_alter_fcmtoken_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
