# Generated by Django 4.2.6 on 2023-12-28 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Must be written with no spaces', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='league', verbose_name='Logo of the league')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Must be written with no spaces', unique=True)),
                ('badge', models.ImageField(blank=True, null=True, upload_to='league', verbose_name='Badge of the team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('updating_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Must be written with no spaces', unique=True)),
                ('number_round', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of round')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('round_state', models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Pending'), (2, 'Finalized')], default=0, verbose_name='State of the round')),
                ('pool', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_bet', models.DecimalField(decimal_places=2, default=0, help_text='This is the amount which will be added to the pool', max_digits=10, verbose_name='Price of the bet')),
                ('fee_bet', models.DecimalField(decimal_places=2, default=0, help_text='This is the amount for the platform', max_digits=7, verbose_name='Fee of the bet')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
