# Generated by Django 4.2.16 on 2024-11-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_round_end_date_alter_round_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
