# Generated by Django 4.2.16 on 2024-11-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_league_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
