# Generated by Django 4.2.16 on 2024-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='acronym',
            field=models.CharField(blank=True, help_text='Shorter way to display team name', max_length=5, null=True),
        ),
    ]
