# Generated by Django 4.2.16 on 2025-02-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_team_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_general_round',
            field=models.BooleanField(default=False),
        ),
    ]
