# Generated by Django 4.2.16 on 2025-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_league_api_league_id_round_api_round_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='badge_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
