# Generated by Django 4.2.16 on 2025-03-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_league_logo_url_team_badge_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leagues',
            field=models.ManyToManyField(related_name='teams', to='league.league'),
        ),
    ]
