# Generated by Django 4.2.16 on 2025-03-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_team_leagues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
    ]
