# Generated by Django 4.2.16 on 2025-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_remove_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='continent',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Americas'), (1, 'Europe'), (2, 'Africa'), (3, 'Asia'), (4, 'Oceania'), (5, 'Tournaments')], default=0),
        ),
    ]
