# Generated by Django 4.2.16 on 2025-04-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_league_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='coins_cost',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
