# Generated by Django 4.2.16 on 2025-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_league_coins_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_cup',
            field=models.BooleanField(default=False, help_text='If True, this league has a Cup format'),
        ),
    ]
