# Generated by Django 4.2.16 on 2025-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_league_is_cup'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Pending'), (2, 'Finalized')], default=0, verbose_name='State of the league'),
        ),
    ]
