# Generated by Django 4.2.16 on 2025-04-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_league_league_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='league.league'),
        ),
    ]
