# Generated by Django 4.2.16 on 2025-09-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_alter_round_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='minimum_coins_first_prize',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='league',
            name='minimum_coins_second_prize',
            field=models.PositiveIntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='league',
            name='minimum_coins_third_prize',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='round',
            name='minimum_coins_first_prize',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='round',
            name='minimum_coins_second_prize',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='round',
            name='minimum_coins_third_prize',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
