# Generated by Django 5.2.9 on 2026-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_league_minimum_coins_first_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='minimum_coins_first_prize',
            field=models.PositiveIntegerField(default=200000),
        ),
        migrations.AlterField(
            model_name='league',
            name='minimum_coins_second_prize',
            field=models.PositiveIntegerField(default=80000),
        ),
        migrations.AlterField(
            model_name='league',
            name='minimum_coins_third_prize',
            field=models.PositiveIntegerField(default=40000),
        ),
        migrations.AlterField(
            model_name='round',
            name='minimum_coins_first_prize',
            field=models.PositiveIntegerField(default=20000),
        ),
        migrations.AlterField(
            model_name='round',
            name='minimum_coins_second_prize',
            field=models.PositiveIntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='round',
            name='minimum_coins_third_prize',
            field=models.PositiveIntegerField(default=4000),
        ),
    ]
