services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout 30 --graceful-timeout 30 --keep-alive 2 --max-requests 500 --max-requests-jitter 50 SoccerPools.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:6
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  celery:
    build: .
    command: celery -A SoccerPools worker --loglevel=info --concurrency=1 --max-tasks-per-child=200 --prefetch-multiplier=1
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  celery-beat:
    build: .
    command: celery -A SoccerPools beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - celery
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data:
